{% set name = "mellon" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce13bcc7f602059d446c9f11203847f5dab7c1d7cee24f3ad019ea8ad08c5bd9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jax
    - jaxopt
    - scikit-learn

test:
  imports:
    - mellon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/settylab/mellon
  summary: Non-parametric density estimator.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - katosh
    - ManuSetty
