{% set name = "mellon" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88dba6a308733650c832cdc61fb717b133b950c1c11ce73552e589840caf809a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jax
    - jaxopt
    - scikit-learn

test:
  imports:
    - mellon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/settylab/mellon
  summary: Non-parametric density estimator.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - katosh
    - ManuSetty
